name: Update packages
on:
  schedule:
  - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: ls test
        run: "ls /home/runner/work/quados-tools/quados-tools"
      - uses: actions/setup-node@v4.0.2
      - uses: pnpm/action-setup@v3.0.0
        with:
          run_install: true
          
      - name: Generate package list
        run: "pnpm generate"
      - uses: EndBug/add-and-commit@v9
